name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./pi5.sln

      - name: Build
        run: dotnet build ./pi5.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./pi5.sln --configuration Release --no-build
        
